<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Hujie Wang">
<meta name="dcterms.date" content="2026-01-17">
<meta name="description" content="From Vision Transformers to Diffusion Transformers: how DiT adapts ViT for image generation">

<title>Diffusion &amp; Flow Matching Part 10: Diffusion Transformers – LayerNorm</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../images/ahead-of-robotics-logo-square.png" rel="icon" type="image/png">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-2a367172f4fe7d9182ebf8e09f85cb4e.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-dark-7fb59815a1c41eec7c034637f0c35ff0.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-2a367172f4fe7d9182ebf8e09f85cb4e.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-121593df2a75119923bedf1cd8a03e8e.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../../site_libs/bootstrap/bootstrap-dark-6fa8e29006c77475f08b454ece139f94.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../../site_libs/bootstrap/bootstrap-121593df2a75119923bedf1cd8a03e8e.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-1RBJ1WWR89"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-1RBJ1WWR89', { 'anonymize_ip': true});
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../../styles.css">
</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../../images/ahead-of-robotics-logo-square.png" alt="" class="navbar-logo light-content">
    <img src="../../../images/ahead-of-robotics-logo-square.png" alt="" class="navbar-logo dark-content">
    </a>
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">LayerNorm</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/timothywangdev/blog"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../../../index.xml"> <i class="bi bi-rss" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#sec-vit" id="toc-sec-vit" class="nav-link active" data-scroll-target="#sec-vit">Vision Transformer (ViT) Primer</a>
  <ul class="collapse">
  <li><a href="#the-vit-architecture" id="toc-the-vit-architecture" class="nav-link" data-scroll-target="#the-vit-architecture">The ViT Architecture</a></li>
  <li><a href="#why-patches-the-quadratic-cost-problem" id="toc-why-patches-the-quadratic-cost-problem" class="nav-link" data-scroll-target="#why-patches-the-quadratic-cost-problem">Why Patches? The Quadratic Cost Problem</a></li>
  <li><a href="#vit-vs-cnns-inductive-bias" id="toc-vit-vs-cnns-inductive-bias" class="nav-link" data-scroll-target="#vit-vs-cnns-inductive-bias">ViT vs CNNs: Inductive Bias</a></li>
  </ul></li>
  <li><a href="#sec-vit-to-dit" id="toc-sec-vit-to-dit" class="nav-link" data-scroll-target="#sec-vit-to-dit">From ViT to DiT</a>
  <ul class="collapse">
  <li><a href="#the-three-key-adaptations" id="toc-the-three-key-adaptations" class="nav-link" data-scroll-target="#the-three-key-adaptations">The Three Key Adaptations</a></li>
  </ul></li>
  <li><a href="#sec-dit" id="toc-sec-dit" class="nav-link" data-scroll-target="#sec-dit">Diffusion Transformer (DiT)</a>
  <ul class="collapse">
  <li><a href="#motivation-why-move-beyond-u-net" id="toc-motivation-why-move-beyond-u-net" class="nav-link" data-scroll-target="#motivation-why-move-beyond-u-net">Motivation: Why Move Beyond U-Net?</a></li>
  <li><a href="#the-dit-architecture" id="toc-the-dit-architecture" class="nav-link" data-scroll-target="#the-dit-architecture">The DiT Architecture</a></li>
  <li><a href="#sec-latent" id="toc-sec-latent" class="nav-link" data-scroll-target="#sec-latent">Why Latent Space is Essential</a></li>
  <li><a href="#sec-adaln" id="toc-sec-adaln" class="nav-link" data-scroll-target="#sec-adaln">Conditioning via AdaLN-Zero</a></li>
  </ul></li>
  <li><a href="#sec-comparison" id="toc-sec-comparison" class="nav-link" data-scroll-target="#sec-comparison">Comparison: U-Net vs DiT</a></li>
  <li><a href="#sec-configs" id="toc-sec-configs" class="nav-link" data-scroll-target="#sec-configs">DiT Model Configurations</a></li>
  <li><a href="#sec-fid" id="toc-sec-fid" class="nav-link" data-scroll-target="#sec-fid">Evaluating Generative Models: FID</a></li>
  <li><a href="#sec-variants" id="toc-sec-variants" class="nav-link" data-scroll-target="#sec-variants">Modern DiT Variants</a></li>
  <li><a href="#sec-summary" id="toc-sec-summary" class="nav-link" data-scroll-target="#sec-summary">Summary</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Diffusion &amp; Flow Matching Part 10: Diffusion Transformers</h1>
  <div class="quarto-categories">
    <div class="quarto-category">diffusion</div>
    <div class="quarto-category">flow-matching</div>
    <div class="quarto-category">generative-models</div>
    <div class="quarto-category">transformer</div>
    <div class="quarto-category">vit</div>
    <div class="quarto-category">dit</div>
    <div class="quarto-category">architecture</div>
  </div>
  </div>

<div>
  <div class="description">
    From Vision Transformers to Diffusion Transformers: how DiT adapts ViT for image generation
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Hujie Wang </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 17, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>TL;DR
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>Vision Transformer (ViT)</strong> treats images as sequences of patches — this enables transformers to process images without convolutions</li>
<li><strong>Diffusion Transformer (DiT)</strong> adapts ViT for diffusion by adding time/class conditioning via AdaLN</li>
<li><strong>Key insight</strong>: DiT = ViT + AdaLN conditioning + latent space operation</li>
<li><strong>Trade-off</strong>: DiT scales better than U-Net but needs more data/compute to overcome weak spatial bias</li>
</ul>
</div>
</div>
<p>In the <a href="../9-unet/">previous post</a>, we covered U-Net — the dominant architecture for diffusion models. But recent work shows that <strong>transformers can match or exceed U-Net performance</strong> while offering better scalability.</p>
<p>This post covers: 1. <strong>Vision Transformer (ViT)</strong> — the foundation that DiT builds upon 2. <strong>Diffusion Transformer (DiT)</strong> — how to adapt ViT for diffusion models 3. <strong>When to use DiT vs U-Net</strong> — practical guidance</p>
<section id="sec-vit" class="level2">
<h2 class="anchored" data-anchor-id="sec-vit">Vision Transformer (ViT) Primer</h2>
<p>Before understanding DiT, we need to understand <strong>Vision Transformer (ViT)</strong> — the architecture it’s built on.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Intuition: The Problem ViT Solves
</div>
</div>
<div class="callout-body-container callout-body">
<p>Transformers revolutionized NLP with attention mechanisms that capture long-range dependencies. But transformers expect <strong>sequences of tokens</strong> — how do you apply them to 2D images?</p>
<p><strong>The breakthrough</strong>: Treat image patches as “visual words.” A 224×224 image split into 16×16 patches becomes a sequence of <span class="math inline">\((224/16)^2 = 196\)</span> tokens. Now standard transformer machinery applies!</p>
</div>
</div>
<section id="the-vit-architecture" class="level3">
<h3 class="anchored" data-anchor-id="the-vit-architecture">The ViT Architecture</h3>
<div id="fig-vit" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-vit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="vit-architecture-original.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-vit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Vision Transformer (ViT) architecture from Dosovitskiy et al.&nbsp;(2020). Left: image is split into patches, linearly projected, combined with position embeddings, and processed by a transformer encoder. A learnable [class] token (position 0) aggregates information for classification. Right: the transformer encoder block structure with layer norm, multi-head attention, MLP, and residual connections.
</figcaption>
</figure>
</div>
<p><strong>Step-by-step</strong>:</p>
<ol type="1">
<li><strong>Patchify</strong>: Split image into non-overlapping <span class="math inline">\(p \times p\)</span> patches
<ul>
<li>Input: <span class="math inline">\(H \times W \times C\)</span> image</li>
<li>Output: <span class="math inline">\(N = (H/p) \times (W/p)\)</span> patches, each of size <span class="math inline">\(p^2 \cdot C\)</span></li>
</ul></li>
<li><strong>Linear embedding</strong>: Project each flattened patch to dimension <span class="math inline">\(d\)</span> <span class="math display">\[z_i = W_{\text{embed}} \cdot \text{flatten}(\text{patch}_i) + b\]</span>
<ul>
<li>This is just a learnable linear layer applied to each patch</li>
</ul></li>
<li><strong>Add position embeddings</strong>: Since attention is permutation-invariant, we must tell the model where each patch came from <span class="math display">\[z_i \leftarrow z_i + e_{\text{pos}}^{(i)}\]</span>
<ul>
<li>Position embeddings are learnable vectors (one per position)</li>
<li>Without this, the model couldn’t distinguish a patch at top-left from bottom-right!</li>
</ul></li>
<li><strong>Prepend [CLS] token</strong>: A special learnable token that aggregates information
<ul>
<li>After processing, the [CLS] token’s output is used for classification</li>
</ul></li>
<li><strong>Transformer encoder</strong>: Stack of identical blocks, each containing:
<ul>
<li>Multi-head self-attention (patches attend to all other patches)</li>
<li>MLP (feed-forward network)</li>
<li>Layer normalization and residual connections</li>
</ul></li>
</ol>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Intuition: What Does Patch Attention Learn?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Just like words “fox” and “jumps” share semantic relationships, visual patches relate to one another:<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<ul>
<li><strong>Texture relationships</strong>: All sky patches attend to each other, learning “blueness” is consistent</li>
<li><strong>Structural relationships</strong>: A horse’s left ear patch attends to its right ear patch, learning symmetry</li>
<li><strong>Semantic relationships</strong>: Wheel patches attend to window patches, learning “car-ness”</li>
</ul>
<p>This global attention — every patch sees every other patch — is what lets ViT capture long-range dependencies that CNNs struggle with.</p>
</div>
</div>
<ol start="6" type="1">
<li><strong>Classification head</strong>: MLP on the final [CLS] token representation</li>
</ol>
</section>
<section id="why-patches-the-quadratic-cost-problem" class="level3">
<h3 class="anchored" data-anchor-id="why-patches-the-quadratic-cost-problem">Why Patches? The Quadratic Cost Problem</h3>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Intuition: Why Not Use Pixels as Tokens?
</div>
</div>
<div class="callout-body-container callout-body">
<p>You might wonder: why not treat each pixel as a token?</p>
<p><strong>The math</strong>: A 224×224 image = 50,176 pixels. Self-attention is <span class="math inline">\(O(n^2)\)</span>, so attention would require <span class="math inline">\(50,176^2 \approx 2.5\)</span> billion operations per layer!</p>
<p><strong>Patches reduce this</strong>: With 16×16 patches, we get only 196 tokens. Attention cost: <span class="math inline">\(196^2 = 38,416\)</span> operations — a <strong>65,000× reduction</strong>.</p>
<p>The trade-off: We lose some fine-grained spatial information, but gain computational tractability.</p>
</div>
</div>
</section>
<section id="vit-vs-cnns-inductive-bias" class="level3">
<h3 class="anchored" data-anchor-id="vit-vs-cnns-inductive-bias">ViT vs CNNs: Inductive Bias</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 47%">
<col style="width: 28%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th>Property</th>
<th>CNNs</th>
<th>ViT</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Local bias</strong></td>
<td>Built-in (kernels are small)</td>
<td>None (attention is global)</td>
</tr>
<tr class="even">
<td><strong>Translation equivariance</strong></td>
<td>Built-in (same kernel everywhere)</td>
<td>Must learn from data</td>
</tr>
<tr class="odd">
<td><strong>Data efficiency</strong></td>
<td>Good (bias helps with limited data)</td>
<td>Poor (needs lots of data)</td>
</tr>
<tr class="even">
<td><strong>Scalability</strong></td>
<td>Limited (hard to scale past ~1B params)</td>
<td>Excellent (scales predictably)</td>
</tr>
</tbody>
</table>
<p><strong>Key insight</strong>: ViT has <strong>weaker inductive bias</strong> than CNNs. This is a disadvantage with limited data (must learn what CNNs get “for free”), but an advantage at scale (fewer constraints on what it can learn).</p>
</section>
</section>
<section id="sec-vit-to-dit" class="level2">
<h2 class="anchored" data-anchor-id="sec-vit-to-dit">From ViT to DiT</h2>
<p>Now we can understand DiT as <strong>ViT adapted for diffusion</strong>. The key question: what changes are needed?</p>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Intuition: What’s Different About Diffusion?
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>ViT for classification</strong>: - Input: image → Output: class label - No conditioning needed (besides the image itself)</p>
<p><strong>DiT for diffusion</strong>: - Input: noisy image → Output: noise prediction (same size as input) - Must condition on timestep <span class="math inline">\(t\)</span> and optionally class <span class="math inline">\(y\)</span> - No [CLS] token needed (we want image output, not a single vector)</p>
</div>
</div>
<section id="the-three-key-adaptations" class="level3">
<h3 class="anchored" data-anchor-id="the-three-key-adaptations">The Three Key Adaptations</h3>
<p><strong>1. Remove [CLS] token, add decoder</strong> - ViT: Uses [CLS] token for classification - DiT: Uses all patch tokens, decodes back to image via linear layer</p>
<p><strong>2. Operate in latent space</strong> (see <a href="../9-unet/#sec-modern">Latent Diffusion in Part 9</a>) - ViT: Works on raw pixels (224×224 is manageable) - DiT: Works on VAE latents (raw 512×512 would be 65,536 tokens!)</p>
<p><strong>3. Add conditioning mechanism (AdaLN)</strong> - ViT: No timestep/class conditioning - DiT: Must inject <span class="math inline">\(t\)</span> and <span class="math inline">\(y\)</span> into every block</p>
</section>
</section>
<section id="sec-dit" class="level2">
<h2 class="anchored" data-anchor-id="sec-dit">Diffusion Transformer (DiT)</h2>
<section id="motivation-why-move-beyond-u-net" class="level3">
<h3 class="anchored" data-anchor-id="motivation-why-move-beyond-u-net">Motivation: Why Move Beyond U-Net?</h3>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Intuition: The Scaling Problem
</div>
</div>
<div class="callout-body-container callout-body">
<p>U-Net works great, so why change? The problem is <strong>scaling</strong>.</p>
<p><strong>U-Net’s issue</strong>: Adding more layers or channels hits diminishing returns. The hierarchical structure (downsampling → bottleneck → upsampling) limits how much compute you can effectively use.</p>
<p><strong>Transformer’s advantage</strong>: It’s just <strong>repeated identical blocks</strong>. Want 2× the compute? Add more layers or wider hidden dimensions. This simplicity makes transformers scale predictably — a property called “scaling laws.”</p>
<p><strong>Trade-off</strong>: Transformers have weaker spatial bias than convolutions. They need more data and compute to learn what convolutions get “for free.” But at massive scale (1000s of GPU-days), transformers win.</p>
</div>
</div>
<p>Recent work shows transformer architectures can exceed U-Net performance:<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
<table class="caption-top table">
<colgroup>
<col style="width: 45%">
<col style="width: 31%">
<col style="width: 22%">
</colgroup>
<thead>
<tr class="header">
<th>Property</th>
<th>U-Net</th>
<th>DiT</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Scaling</strong></td>
<td>Diminishing returns past ~1B params</td>
<td>Predictable: 2× compute → better FID</td>
</tr>
<tr class="even">
<td><strong>Design</strong></td>
<td>Complex (skip connections, multi-resolution)</td>
<td>Simple (stack identical blocks)</td>
</tr>
<tr class="odd">
<td><strong>Spatial bias</strong></td>
<td>Strong (convolutions)</td>
<td>Weak (must learn from data)</td>
</tr>
<tr class="even">
<td><strong>Best for</strong></td>
<td>Limited compute, few data</td>
<td>Massive compute, lots of data</td>
</tr>
</tbody>
</table>
</section>
<section id="the-dit-architecture" class="level3">
<h3 class="anchored" data-anchor-id="the-dit-architecture">The DiT Architecture</h3>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Intuition: How Transformers See Images
</div>
</div>
<div class="callout-body-container callout-body">
<p>Transformers expect <strong>sequences of tokens</strong> (like words in a sentence). But images are 2D grids!</p>
<p><strong>The solution</strong>: Split the image into non-overlapping patches and treat each patch as a “visual word.”</p>
<p><strong>Example</strong>: A 256×256 image with 16×16 patches becomes <span class="math inline">\((256/16)^2 = 256\)</span> tokens. Now the transformer can process it just like a sentence of 256 words!</p>
<p><strong>The catch</strong>: Attention is <span class="math inline">\(O(n^2)\)</span> in sequence length. A 512×512 image with 16×16 patches = 1024 tokens = 1 million attention computations per layer. This is why DiT operates in <strong>latent space</strong> (more on this below).</p>
</div>
</div>
<div id="fig-dit-patchify" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-dit-patchify-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="dit-patchify.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-dit-patchify-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: DiT pipeline: VAE latent (64×64×4) is split into patches, linearly embedded into tokens with positional encoding, processed through transformer blocks with AdaLN conditioning, then decoded back to latent space.
</figcaption>
</figure>
</div>
<p>DiT adapts Vision Transformer (ViT) for diffusion:<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></p>
<ol type="1">
<li><strong>Patchify</strong>: Split latent into <span class="math inline">\(p \times p\)</span> non-overlapping patches</li>
<li><strong>Embed</strong>: Linear projection maps each patch to a token vector (dimension <span class="math inline">\(d\)</span>)</li>
<li><strong>Add position</strong>: Learnable position embeddings tell the model where each patch came from</li>
<li><strong>Process</strong>: Stack of transformer blocks (self-attention + MLP)</li>
<li><strong>Decode</strong>: Linear layer maps tokens back to patches, reshape to image</li>
</ol>
</section>
<section id="sec-latent" class="level3">
<h3 class="anchored" data-anchor-id="sec-latent">Why Latent Space is Essential</h3>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Intuition: The Sequence Length Problem
</div>
</div>
<div class="callout-body-container callout-body">
<p>Running DiT in pixel space is prohibitively expensive. Here’s why:</p>
<p><strong>Pixel space</strong>: 256×256×3 image with patch size 2 → <span class="math inline">\((256/2)^2 = 16,384\)</span> tokens <strong>Attention cost</strong>: <span class="math inline">\(16,384^2 \approx 270\)</span> million operations per layer!</p>
<p><strong>Latent space</strong>: VAE compresses 256×256×3 → 32×32×4, then patch size 2 → <span class="math inline">\((32/2)^2 = 256\)</span> tokens <strong>Attention cost</strong>: <span class="math inline">\(256^2 = 65,536\)</span> operations per layer</p>
<p>That’s a <strong>4000× reduction</strong> in attention cost. Latent diffusion isn’t optional for DiT — it’s essential.</p>
</div>
</div>
<div id="fig-latent-diffusion-dit" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-latent-diffusion-dit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="latent-diffusion-original.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-latent-diffusion-dit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Latent Diffusion Model architecture from Rombach et al.&nbsp;(2022). Images are encoded to latent space <span class="math inline">\(z\)</span> via encoder <span class="math inline">\(\mathcal{E}\)</span>, diffusion operates in this compressed space with optional conditioning via cross-attention, then decoder <span class="math inline">\(\mathcal{D}\)</span> reconstructs the output.
</figcaption>
</figure>
</div>
<p><strong>Patch size trade-off</strong>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Patch Size</th>
<th>Tokens (from 64×64 latent)</th>
<th>Quality</th>
<th>Compute</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2</td>
<td>1024</td>
<td>Best (FID 2.27)</td>
<td>Highest</td>
</tr>
<tr class="even">
<td>4</td>
<td>256</td>
<td>Good</td>
<td>Medium</td>
</tr>
<tr class="odd">
<td>8</td>
<td>64</td>
<td>Lower</td>
<td>Fastest</td>
</tr>
</tbody>
</table>
</section>
<section id="sec-adaln" class="level3">
<h3 class="anchored" data-anchor-id="sec-adaln">Conditioning via AdaLN-Zero</h3>
<p>Now for the key question: how does DiT handle time <span class="math inline">\(t\)</span> and class label <span class="math inline">\(y\)</span>?</p>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Intuition: Why Not Just Add Tokens?
</div>
</div>
<div class="callout-body-container callout-body">
<p>The obvious approach: add <span class="math inline">\(t\)</span> and <span class="math inline">\(y\)</span> as extra tokens in the sequence. But this wastes capacity — every layer processes these tokens even though their values never change!</p>
<p><strong>AdaLN’s insight</strong>: Instead of adding tokens, <strong>modulate the layer normalization</strong>. The conditioning doesn’t participate in attention — it just adjusts how the layers process features.</p>
<p><strong>Analogy</strong>: Think of an audio equalizer. The EQ settings don’t become part of the music — they adjust the gain and tone of what’s playing. AdaLN adjusts the “gain and tone” of each layer based on timestep and class.</p>
</div>
</div>
<div id="fig-adaln" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-adaln-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="adaln-mechanism.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-adaln-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: AdaLN mechanism: timestep <span class="math inline">\(t\)</span> and condition <span class="math inline">\(y\)</span> are embedded and processed by an MLP to produce 6 parameters (<span class="math inline">\(\gamma\)</span>, <span class="math inline">\(\beta\)</span> for scale/shift, <span class="math inline">\(\alpha\)</span> for gating) that modulate how each transformer block processes features.
</figcaption>
</figure>
</div>
<p><strong>How AdaLN works</strong> — For each transformer block:</p>
<ol type="1">
<li><strong>Embed conditioning</strong>: <span class="math inline">\(c = \text{MLP}(e_t + e_y)\)</span> where <span class="math inline">\(e_t, e_y\)</span> are time/class embeddings</li>
<li><strong>Predict 6 parameters</strong>: <span class="math inline">\((\gamma_1, \beta_1, \alpha_1, \gamma_2, \beta_2, \alpha_2) = \text{Linear}(c)\)</span></li>
<li><strong>Modulate attention branch</strong>:
<ul>
<li>Scale and shift after LayerNorm: <span class="math inline">\(x' = \gamma_1 \cdot \text{LN}(x) + \beta_1\)</span></li>
<li>Gate the residual: <span class="math inline">\(x = x + \alpha_1 \cdot \text{Attention}(x')\)</span></li>
</ul></li>
<li><strong>Modulate MLP branch</strong>:
<ul>
<li>Scale and shift: <span class="math inline">\(x' = \gamma_2 \cdot \text{LN}(x) + \beta_2\)</span></li>
<li>Gate the residual: <span class="math inline">\(x = x + \alpha_2 \cdot \text{MLP}(x')\)</span></li>
</ul></li>
</ol>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Intuition: Why “Zero” in AdaLN-Zero?
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <span class="math inline">\(\alpha\)</span> (gating) parameters are initialized to <strong>zero</strong>. This means at initialization, each DiT block computes: <span class="math display">\[x_{\text{out}} = x + 0 \cdot \text{Attention}(x) = x\]</span></p>
<p>The block is an <strong>identity function</strong> — it just passes the input through unchanged! This makes training 28-layer networks stable because the model starts simple and gradually learns to use each layer.</p>
<p><strong>Why this works so well</strong>: Research shows that zero-initialized weights gradually converge to a Gaussian-like distribution during training.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a> This smooth convergence is more stable than random initialization — the network learns to “turn on” conditioning gradually rather than starting with noisy modulation.</p>
</div>
</div>
<p><strong>Why AdaLN-Zero wins</strong>:<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a></p>
<table class="caption-top table">
<colgroup>
<col style="width: 19%">
<col style="width: 31%">
<col style="width: 14%">
<col style="width: 34%">
</colgroup>
<thead>
<tr class="header">
<th>Method</th>
<th>How it works</th>
<th>Cost</th>
<th>ImageNet FID</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>In-context</strong></td>
<td>Append <span class="math inline">\(t\)</span>, <span class="math inline">\(y\)</span> as extra tokens</td>
<td><span class="math inline">\(O(d)\)</span></td>
<td>5.67</td>
</tr>
<tr class="even">
<td><strong>Cross-attention</strong></td>
<td>Attend over condition embeddings</td>
<td><span class="math inline">\(O(d^2)\)</span></td>
<td>3.75</td>
</tr>
<tr class="odd">
<td><strong>AdaLN</strong></td>
<td>Modulate LayerNorm scale/shift</td>
<td><span class="math inline">\(O(d)\)</span></td>
<td>2.98</td>
</tr>
<tr class="even">
<td><strong>AdaLN-Zero</strong></td>
<td>AdaLN + zero-init gating</td>
<td><span class="math inline">\(O(d)\)</span></td>
<td><strong>2.27</strong></td>
</tr>
</tbody>
</table>
<p><strong>Note on text conditioning</strong>: For free-form text prompts (not class labels), cross-attention works better than AdaLN. This is what Stable Diffusion uses — the text encoder outputs a sequence of embeddings, and each DiT block cross-attends to them. See <a href="../9-unet/">Part 9</a> for more on how conditioning flows through the network.</p>
</section>
</section>
<section id="sec-comparison" class="level2">
<h2 class="anchored" data-anchor-id="sec-comparison">Comparison: U-Net vs DiT</h2>
<div id="fig-comparison" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="unet-vs-dit-comparison.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Architectural comparison: U-Net uses hierarchical multi-scale processing with skip connections (top) vs.&nbsp;DiT’s flat architecture with global attention across all patches (bottom).
</figcaption>
</figure>
</div>
<div class="callout callout-style-simple callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>When to Use Each
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Use U-Net if:</strong> - You’re training on limited compute (&lt; 100 GPU-days) - Working in pixel space (not latent diffusion) - You need strong performance out-of-the-box with less data - Example: Fine-tuning Stable Diffusion on a custom domain</p>
<p><strong>Use DiT if:</strong> - You have massive compute and data (foundation model scale) - Working in latent space with a pretrained VAE - You want best-in-class scalability and are willing to pay the compute cost - Example: Training a class-conditional ImageNet model from scratch</p>
</div>
</div>
<p>Here’s how the architectures compare:<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a></p>
<table class="caption-top table">
<colgroup>
<col style="width: 40%">
<col style="width: 35%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Aspect</th>
<th>U-Net</th>
<th>DiT</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Inductive bias</strong></td>
<td>Strong (convolution = local, translation-invariant)</td>
<td>Weak (attention = global, permutation-invariant)</td>
</tr>
<tr class="even">
<td><strong>Scalability</strong></td>
<td>Diminishing returns past ~1B parameters</td>
<td>Predictable scaling: 2× compute → better FID</td>
</tr>
<tr class="odd">
<td><strong>Training cost</strong></td>
<td>Lower (100s of GPU-days for Stable Diffusion)</td>
<td>Higher (1000s of GPU-days for DiT-XL/2)</td>
</tr>
<tr class="even">
<td><strong>Sample quality (@ equivalent cost)</strong></td>
<td>Better on small/mid budgets</td>
<td>Better at massive scale</td>
</tr>
<tr class="odd">
<td><strong>Conditioning</strong></td>
<td>Ad-hoc (inject time, add cross-attn for text)</td>
<td>Principled (AdaLN, cross-attn, or in-context)</td>
</tr>
<tr class="even">
<td><strong>Architecture complexity</strong></td>
<td>High (skip connections, resolution-dependent attn)</td>
<td>Low (repeat identical blocks)</td>
</tr>
<tr class="odd">
<td><strong>Memory efficiency</strong></td>
<td>Better (hierarchical = smaller feature maps)</td>
<td>Worse (all patches processed at full resolution)</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-simple callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Common Misconception
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>“Transformers are always better than CNNs”</strong> — Not true for diffusion! U-Nets remain state-of-the-art for many applications because they encode strong spatial priors. DiT only wins when you have enough data and compute to overcome its lack of inductive bias.<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a></p>
</div>
</div>
<p><strong>Empirical result</strong>: DiT-XL/2 achieves FID 2.27 on ImageNet 256×256, beating the previous best (LDM) of 3.60. But this required training on 256 TPU-v3 cores — far more than U-Net baselines.<a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a></p>
</section>
<section id="sec-configs" class="level2">
<h2 class="anchored" data-anchor-id="sec-configs">DiT Model Configurations</h2>
<p>DiT comes in four configurations borrowed from ViT:<a href="#fn10" class="footnote-ref" id="fnref10" role="doc-noteref"><sup>10</sup></a></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Model</th>
<th>Hidden Dim</th>
<th>Depth</th>
<th>Heads</th>
<th>Parameters</th>
<th>Gflops</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>DiT-S</td>
<td>384</td>
<td>12</td>
<td>6</td>
<td>33M</td>
<td>0.4</td>
</tr>
<tr class="even">
<td>DiT-B</td>
<td>768</td>
<td>12</td>
<td>12</td>
<td>130M</td>
<td>5.6</td>
</tr>
<tr class="odd">
<td>DiT-L</td>
<td>1024</td>
<td>24</td>
<td>16</td>
<td>458M</td>
<td>35.6</td>
</tr>
<tr class="even">
<td>DiT-XL</td>
<td>1152</td>
<td>28</td>
<td>16</td>
<td>675M</td>
<td>119</td>
</tr>
</tbody>
</table>
<p>The naming follows ViT conventions (S=Small, B=Base, L=Large, XL=Extra Large), and the configs were chosen based on ViT scaling research.</p>
</section>
<section id="sec-fid" class="level2">
<h2 class="anchored" data-anchor-id="sec-fid">Evaluating Generative Models: FID</h2>
<p>We’ve mentioned “FID 2.27” several times — but what does this actually mean?</p>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Intuition: How Do You Measure Image Quality?
</div>
</div>
<div class="callout-body-container callout-body">
<p>You can’t just compare generated images to training images pixel-by-pixel (that would penalize valid variations). Instead, we compare <strong>high-level features</strong> — does the model generate things that “look like” real images at a semantic level?</p>
<p><strong>Fréchet Inception Distance (FID)</strong> does exactly this:<a href="#fn11" class="footnote-ref" id="fnref11" role="doc-noteref"><sup>11</sup></a> 1. Pass real images through a pretrained Inception network → get feature vectors 2. Pass generated images through the same network → get feature vectors 3. Compare the <strong>distributions</strong> of these features (mean and covariance)</p>
</div>
</div>
<p><strong>How FID works</strong>:<a href="#fn12" class="footnote-ref" id="fnref12" role="doc-noteref"><sup>12</sup></a></p>
<ol type="1">
<li><strong>Extract features</strong>: Use Inception v3’s 2048-dimensional penultimate layer activations</li>
<li><strong>Assume Gaussian</strong>: Model both real and generated feature distributions as multivariate Gaussians</li>
<li><strong>Compute distance</strong>: Calculate the Fréchet distance between the two Gaussians: <span class="math display">\[\text{FID} = \|\mu_r - \mu_g\|^2 + \text{Tr}(\Sigma_r + \Sigma_g - 2(\Sigma_r \Sigma_g)^{1/2})\]</span> where <span class="math inline">\((\mu_r, \Sigma_r)\)</span> and <span class="math inline">\((\mu_g, \Sigma_g)\)</span> are the mean/covariance of real and generated features</li>
</ol>
<p><strong>Interpreting FID scores</strong>: - <strong>Lower is better</strong> — FID = 0 means identical distributions - <strong>ImageNet benchmarks</strong>: FID &lt; 5 is excellent, FID &lt; 10 is good - DiT-XL/2 achieves <strong>FID 2.27</strong> on ImageNet 256×256 (state-of-the-art as of 2023)</p>
<p><strong>Why FID over other metrics?</strong><a href="#fn13" class="footnote-ref" id="fnref13" role="doc-noteref"><sup>13</sup></a> - <strong>Inception Score (IS)</strong>: Only looks at generated images, ignores real data distribution - <strong>FID</strong>: Compares generated vs real — captures both quality AND diversity - <strong>Limitation</strong>: Assumes Gaussian features, biased on small samples</p>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>Note</strong>: FID is computed on a specific dataset (usually ImageNet) with specific image resolution. FID scores aren’t directly comparable across different datasets or resolutions.</p>
</div>
</div>
</div>
</section>
<section id="sec-variants" class="level2">
<h2 class="anchored" data-anchor-id="sec-variants">Modern DiT Variants</h2>
<p>DiT has become the backbone for several state-of-the-art models. Recent research has also improved the core conditioning mechanism — <strong>adaLN-Gaussian</strong> initializes modulation weights from Gaussian distributions (instead of zero), yielding a 2.16% FID improvement over AdaLN-Zero.<a href="#fn14" class="footnote-ref" id="fnref14" role="doc-noteref"><sup>14</sup></a></p>
<p><strong>Stable Diffusion 3 (SD3)</strong>: - Uses “Multi-Modal Diffusion Transformer” (MM-DiT) - Separate transformer streams for text and image, with cross-attention - Text conditioning via T5 and CLIP embeddings</p>
<p><strong>Flux</strong>: - Builds on DiT with improved text understanding - Uses rectified flow instead of DDPM-style diffusion - T5 + CLIP ensemble for text encoding</p>
<p><strong>Sora</strong> (OpenAI): - Video generation using DiT - Treats video as sequence of patch tokens across space and time - Enables variable resolution and duration</p>
</section>
<section id="sec-summary" class="level2">
<h2 class="anchored" data-anchor-id="sec-summary">Summary</h2>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Key Takeaways
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Vision Transformer (ViT)</strong>: - Treats images as patch sequences, enabling transformers for vision - Key components: patchify → linear embed → position encoding → transformer blocks → classifier - Weaker inductive bias than CNNs (must learn locality), but scales better</p>
<p><strong>Diffusion Transformer (DiT)</strong>: - DiT = ViT adapted for diffusion (no [CLS] token, adds decoder, adds AdaLN) - <strong>AdaLN-Zero</strong>: Inject timestep/class by modulating LayerNorm parameters, not adding tokens - Zero initialization of gating parameters → blocks start as identity → stable training - Must operate in latent space (4000× attention cost reduction)</p>
<p><strong>When to use DiT vs U-Net</strong>: - U-Net: Limited compute, pixel space, need spatial bias - DiT: Massive compute, latent space, want scaling laws</p>
<p><strong>The bigger picture</strong>: U-Net and DiT are different ways to parameterize the same math (<span class="math inline">\(u_\theta(x_t, t)\)</span>). The architecture choice is about trade-offs: inductive bias vs scalability, data efficiency vs ultimate performance.</p>
</div>
</div>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<p><strong>Foundational Papers:</strong></p>
<ul>
<li>Dosovitskiy, A., et al.&nbsp;(2020). <a href="https://arxiv.org/abs/2010.11929">An Image is Worth 16x16 Words: Transformers for Image Recognition at Scale</a>. <em>ICLR 2021</em>. (ViT)</li>
<li>Peebles, W., &amp; Xie, S. (2023). <a href="https://arxiv.org/abs/2212.09748">Scalable Diffusion Models with Transformers</a>. <em>ICCV 2023</em>. (DiT)</li>
<li>Dhariwal, P., &amp; Nichol, A. (2021). <a href="https://arxiv.org/abs/2105.05233">Diffusion Models Beat GANs on Image Synthesis</a>. <em>NeurIPS 2021</em>.</li>
</ul>
<p><strong>Latent Diffusion:</strong></p>
<ul>
<li>Rombach, R., et al.&nbsp;(2022). <a href="https://arxiv.org/abs/2112.10752">High-Resolution Image Synthesis with Latent Diffusion Models</a>. <em>CVPR 2022</em>. (Stable Diffusion)</li>
</ul>
<p><strong>Educational Resources:</strong></p>
<ul>
<li>Encord. <a href="https://encord.com/blog/diffusion-models-with-transformers/">Diffusion Transformer (DiT) Models: A Beginner’s Guide</a>. Blog post.</li>
<li>Lightly AI. <a href="https://www.lightly.ai/blog/diffusion-transformers-dit">Diffusion Transformers Explained: The Beginner’s Guide</a>. Blog post.</li>
<li>DiT Project Page. <a href="https://www.wpeebles.com/DiT">Scalable Diffusion Models with Transformers</a>. Official project page.</li>
<li>APXML. <a href="https://apxml.com/courses/advanced-diffusion-architectures/chapter-3-transformer-diffusion-models/unet-vs-transformer-diffusion">U-Net vs Transformer Comparison for Diffusion</a>. Course material.</li>
<li>Towards Data Science. <a href="https://towardsdatascience.com/diffusion-transformer-explained-e603c4770f7e/">Diffusion Transformer Explained</a>. Comprehensive walkthrough.</li>
<li>Pinecone. <a href="https://www.pinecone.io/learn/series/image-search/vision-transformers/">Vision Transformers (ViT) Explained</a>. Excellent visual explanations of patch embeddings and attention.</li>
<li>AI Summer. <a href="https://theaisummer.com/vision-transformer/">How the Vision Transformer (ViT) works in 10 minutes</a>. Concise tutorial.</li>
</ul>


</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p><a href="https://arxiv.org/abs/2010.11929">Dosovitskiy et al., 2020</a><a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p><a href="https://www.pinecone.io/learn/series/image-search/vision-transformers/">Pinecone, “Vision Transformers Explained”</a><a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p><a href="https://arxiv.org/abs/2212.09748">Peebles &amp; Xie, 2023</a><a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p><a href="https://encord.com/blog/diffusion-models-with-transformers/">Encord, “Diffusion Transformer Models Guide”</a><a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p><a href="https://openreview.net/forum?id=E4roJSM9RM">OpenReview, “Unveiling the Secret of AdaLN-Zero”</a><a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p><a href="https://arxiv.org/abs/2212.09748">Peebles &amp; Xie, 2023</a><a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p><a href="https://apxml.com/courses/advanced-diffusion-architectures/chapter-3-transformer-diffusion-models/unet-vs-transformer-diffusion">APXML, “U-Net vs Transformer Comparison”</a><a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p><a href="https://arxiv.org/abs/2105.05233">Dhariwal &amp; Nichol, 2021</a><a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn9"><p><a href="https://arxiv.org/abs/2212.09748">Peebles &amp; Xie, 2023</a><a href="#fnref9" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn10"><p><a href="https://arxiv.org/abs/2212.09748">Peebles &amp; Xie, 2023</a><a href="#fnref10" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn11"><p><a href="https://arxiv.org/abs/1706.08500">Heusel et al., 2017</a><a href="#fnref11" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn12"><p><a href="https://machinelearningmastery.com/how-to-implement-the-frechet-inception-distance-fid-from-scratch/">Machine Learning Mastery, “FID for Evaluating GANs”</a><a href="#fnref12" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn13"><p><a href="https://en.wikipedia.org/wiki/Fr%C3%A9chet_inception_distance">Wikipedia, “Fréchet Inception Distance”</a><a href="#fnref13" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn14"><p><a href="https://openreview.net/forum?id=E4roJSM9RM">OpenReview, “Unveiling the Secret of AdaLN-Zero”</a><a href="#fnref14" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/layernorm\.dev");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<input type="hidden" id="giscus-base-theme" value="light">
<input type="hidden" id="giscus-alt-theme" value="dark_dimmed">
<script>
  function loadGiscus() {
    // Function to get the theme based on body class
    const getTheme = () => {
      let baseTheme = document.getElementById('giscus-base-theme').value;
      let altTheme = document.getElementById('giscus-alt-theme').value;
      if (authorPrefersDark) {
          [baseTheme, altTheme] = [altTheme, baseTheme];
      }
      return document.body.classList.contains('quarto-dark') ? altTheme : baseTheme;
    };
    const script = document.createElement("script");
    script.src = "https://giscus.app/client.js";
    script.async = true;
    script.dataset.repo = "timothywangdev/blog";
    script.dataset.repoId = "MDEwOlJlcG9zaXRvcnkyNjIyMTE2OTI=";
    script.dataset.category = "Announcements";
    script.dataset.categoryId = "DIC_kwDOD6EIbM4CzgxQ";
    script.dataset.mapping = "pathname";
    script.dataset.reactionsEnabled = "1";
    script.dataset.emitMetadata = "0";
    script.dataset.inputPosition = "bottom";
    script.dataset.theme = getTheme();
    script.dataset.lang = "en";
    script.crossOrigin = "anonymous";
    // Append the script to the desired div instead of at the end of the body
    document.getElementById("quarto-content").appendChild(script);
  }
  loadGiscus();
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>Copyright 2025, LayerNorm</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>