project:
  type: website
  resources:
    - "CNAME"

website:
  title: "Foundation Models & Robotics"
  description: "Exploring state-of-the-art AI models"
  site-url: https://layernorm.dev
  favicon: images/ahead-of-robotics-logo-square.png
  google-analytics: "G-1RBJ1WWR89"
  navbar:
    logo: images/ahead-of-robotics-logo-square.png
    right:
      - about.qmd
      - icon: github
        href: https://github.com/timothywangdev/blog
      - icon: rss
        href: index.xml
  page-footer:
    center: "Copyright 2025, Foundation Models & Robotics"

format:
  html:
    theme:
      light: [flatly, custom-theme.scss]
      dark: [darkly, custom-theme.scss]
    highlight-style: atom-one
    code-copy: true
    code-overflow: wrap
    css: styles.css
    toc: true

comments:
  giscus:
    repo: timothywangdev/blog
    repo-id: MDEwOlJlcG9zaXRvcnkyNjIyMTE2OTI=
    category: Announcements
    category-id: DIC_kwDOD6EIbM4CzgxQ
    mapping: pathname
    reactions-enabled: true
    input-position: bottom
    theme:
      light: light
      dark: dark_dimmed
    loading: lazy
