project:
  type: website

website:
  title: "LayerNorm"
  description: "Exploring state-of-the-art AI models"
  site-url: https://layernorm.dev
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/timothywangdev/blog
      - icon: rss
        href: index.xml
  page-footer:
    center: "Copyright 2025, LayerNorm"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    highlight-style: atom-one
    code-copy: true
    code-overflow: wrap
    css: styles.css
    toc: true
