---
title: "如果你是ACMer,你会选择哪个职业?【转自某牛博客】（巨搞！）"
date: "2011-12-05"
categories: [miscellaneous, imported]
draft: false
---

# 

下午受ACM-DIY群里的大神们的启发YY了一套ACMer的技能. 以下十个职业参照WoW.如果你是ACMer,你会选择哪个职业? 战士: 拦截:阻止对方一个AC. 战斗怒吼:友方程序效率提高100%,持续10分钟 断筋:使对方无法提交,持续20分钟 雷霆一击:周围目标程序效率降低99%,持续10分钟 致死打击:过了80%数据就算AC 缴械:没收敌人键盘,持续20分钟 嘲讽:所有人都不断提交你刚刚提交的题,持续1分钟 法师: 奥术光辉:队友智商提高30%,持续60分钟 奥术智慧:智商提高200%,持续20分钟 法术偷取:偷取目标一个技能 寒冰护体:使一个提交TLE的程序继续运行5分 寒冰箭:使对方APM降低80%,持续20分钟 召唤debug:召唤智商为你80%的小弟帮你debug 火球术:烧掉对方纸质模板 牧师: 群体驱散:驱散队友身上不良效果 精神鞭笞:指定对方一名脑残5分钟 次级治疗术:消除最近一次非AC提交 强效治疗术:去除20分钟内的非AC提交 精神控制:控制目标为自己想题20分钟 沉默:目标停止交流10分钟 暗言术:20%概率直接AC,80%自己去WC面壁20分钟 盗贼: 毒害:使对方腹泻20分钟,奖励一个连击点 脚踢:踢掉对方电源线,奖励一个连击点 致盲:目标失眠10分钟,奖励一个连击点 凿击:扣掉对方键盘上一个按键,奖励一个连击点 背刺:于对方上厕所时进行背刺,使其僵硬20分钟,奖励一个连击点 潜行:偷看对方代码,但记忆力下降25%,奖励一个连击点 伏击(终结技):当对方提交AC后,你马上提交此题,可以把他的AC变成是你的,消耗三个连击点 猎人: 误导:使大家一开场30分钟都去做神题 毒蛇陷阱:目标每AC一题他边上出现一条蛇 代码印记:找一个目标,使他在键盘敲打的代码同时在你这边显示 假死:使你在Ranklist上消失,消除你对别人的威胁 献祭陷阱:在WC门口放置陷阱,使目标之前的思路消失并转移到你脑子里 猫鼬撕咬:召唤苏格兰折耳猫在你边上卖萌 扰乱攻击:在目标边上放忐忑 德鲁伊: 清晰预兆:预言15分钟后的Ranklist 愈合:每30分钟取消一个非AC提交 宁静:消除所有干扰 冥想:接下去的20分钟相当于20小时 畏缩:使对方不敢提交你刚刚交的题 猫咪形态:变身苏格兰折耳猫到对方键盘上卖萌,骚扰+偷看代码 教主形态:教主附体30分钟 萨满: 闪电之盾:当别人AC你WA的题目后麻痹20分钟 地缚图腾:缚住目标双手,迫使其用脸滚键盘10分钟 视界术:使视点切换到目标区域 嗜血:APM提到200%,持续20分钟 石化图腾:石化目标键盘10分钟 熔岩图腾:使目标键盘温度达到100度,持续10分钟 先祖之魂:召唤已故的神牛附体 术士: 献祭:你周围的队伍每20分钟多一次罚时 召唤小鬼:召唤你智商80%的小鬼帮你出例子 智力通道:永久减少1%的智商,换1AC 吸取智力:吸收目标20%的智商,60分钟 末日守卫:召唤末日守卫指定一题60分钟内无法AC 末日灾祸:可以在封板后选择结束比赛 WC灾祸:全场队伍集体上WC5分钟 圣骑士: 圣佑术:你的罚时算10分钟 洞察圣印:直接看出一题的算法 异端裁决:替换一个评判结果 牺牲之手:全场比赛都只使用一支手打字,加一道题AC 圣盾术:20分钟内提交不算罚时 愤怒之锤:罚时次数达到50次之后可以到出题人身上泄愤 教主祝福:教主在边上指导balabalabala…. 死亡骑士: 亡者大军:召唤100个已故的会A-B水平的菜鸟给你出例子 血液沸腾:使范围内所有人血液沸腾,流鼻血 鲜血AC:自己流500cc鼻血后增加一道AC 传染:把自己的SB错误传染给被人 爆发:封板后智商大增200% 枯萎凋零:范围内目标每60分钟凋零一道AC 复活盟友:如果队友不乖,你可以干掉他然后复活来听自己的命令 (所有技能限定使用一次) 
