---
title: "今天看了下11年ACM的队名，我彻底无语了。。。。。。"
date: "2012-01-09"
categories: [miscellaneous, imported]
draft: false
---

学校排名 | 学校名称 | 队伍排名 | 队伍名  
---|---|---|---  
1 | 上海交通大学 | 1 | 史诗 (team29)  
2 | 清华大学 | 2 | DivineRapier (team4)  
* | 清华大学 | 3 | machinator (team88)  
3 | 中山大学 | 4 | SYSU_Metalgarurumon (team94)  
4 | 复旦大学 | 5 | FDU_BGM (team5)  
5 | 浙江工业大学 | 6 | 小和山职业技术学院 (team33)  
6 | 电子科技大学 | 7 | 成电-宙斯 (team18)  
7 | 北京大学 | 8 | 巴斯特 (team14)  
| 北京大学 | 9 | 若爆了 (team27)  
8 | 国防科技大学 | 10 | 阿蕾泡菜 (team52)  
| 北京大学 | 11 | 丽华 (team106)  
| 北京大学 | 12 | OSU (team48)  
9 | 武汉大学 | 13 | 旅途 (team25)  
| 电子科技大学 | 14 | 成电-阿波罗 (team57)  
| 中山大学 | 15 | SYSU_HolyAngemon (team11)  
| 中山大学 | 16 | SYSU_AtlurKabuterimon (team51)  
| 复旦大学 | 17 | FDU_Sanguosha (team43)  
| 北京大学 | 18 | OSU安格瑞扣得死 (team121)  
10 | 北京航空航天大学 | 19 | 北航-1 (team16)  
11 | 西安电子科技大学 | 20 | XDU_ Avalon (team12)  
12 | 哈尔滨工业大学 | 21 | 史诗 (team28)  
13 | 天津大学 | 22 | 哎呦喂~ (team13)  
14 | 北京邮电大学 | 23 | 魔女 (team145)  
| 清华大学 | 24 | Odds (team41)  
15 | 南京理工大学 | 25 | STSky (team10)  
* | 华东理工大学 | 26 | 哆啦A梦 (team61)  
| 复旦大学 | 27 | Buer (team83)  
| 北京邮电大学 | 28 | 逐日者 (team38)  
16 | 杭州电子科技大学 | 29 | 我知道你喜欢我 (team153)  
17 | 福州大学 | 30 | 编译器 (team55)  
18 | 西南民族大学 | 31 | SWUN_Snow_storm (team130)  
19 | 北京师范大学 | 32 | 雷霆 (team24)  
20 | 蒙古国立大学 | 33 | S.M.C.S (team91)  
21 | 中国人民大学 | 34 | 人大金仓 (team147)  
22 | 华南农业大学 | 35 | SCAU_病了 (team50)  
23 | 湘潭大学 | 36 | 湘潭大学10号队 (team32)  
* | 国防科技大学 | 37 | 阿蕾泡醋 (team133)  
| 武汉大学 | 38 | 你信吗 (team109)  
24 | 湖南大学 | 39 | 旅行者 (team107)  
25 | 中国科学技术大学 | 40 | 开源 (team23)  
| 哈尔滨工业大学 | 41 | 奔跑， 运行， 一击脱离 (team54)  
26 | 西安交通大学 | 42 | FollowDream (team44)  
27 | 华东交通大学 | 43 | 素数音乐 (team74)  
28 | 广东工业大学 | 44 | 多拉AC梦 (team60)  
29 | 华中科技大学 | 45 | HUST_lol (team8)  
| 电子科技大学 | 46 | 成电-缪斯 (team134)  
| 福州大学 | 47 | 歪歪 (team115)  
| 北京航空航天大学 | 48 | 我们喜欢气球。.. (team116)  
30 | 北京交通大学 | 49 | 缘分天使 (team117)  
| 华中科技大学 | 50 | HUST_DONE (team87)  
* | 大连理工大学 | 51 | 一帆风顺 (team35)  
| 北京师范大学 | 52 | Attiix (team42)  
| 天津大学 | 53 | 逗你玩～ (team59)  
* | 山东大学 | 54 | S.O.G (team49)  
* | 福建师范大学 | 55 | 灵魂链 (team143)  
31 | 浙江大学城市学院 | 56 | 造神奇 (team118)  
* | 大连理工大学 | 57 | 蠕虫 (team110)  
* | 大连理工大学 | 58 | 使徒 (team30)  
32 | 山东大学 | 59 | Ace Coders (team122)  
33 | 南京大学 | 60 | Heracles (team85)  
34 | 吉林大学 | 61 | GAP (team7)  
| 北京交通大学 | 62 | Only (team69)  
| 华中科技大学 | 63 | HUST_Cutit (team45)  
35 | 南阳理工学院 | 64 | Lambda (team47)  
36 | 东北林业大学 | 65 | 穿越火线 (team135)  
37 | 东北师范大学 | 66 | 苦艾酒 (team104)  
38 | 厦门大学 | 67 | 伙伴系统 (team103)  
39 | 华东理工大学 | 68 | 超级漏洞 (team17)  
40 | 华南师范大学 | 69 | SCNU_Cindy_Prinse (team9)  
41 | 北京林业大学 | 70 | 无压力 (team76)  
* | 天津大学 | 71 | TJU_Orion (team132)  
| 吉林大学 | 72 | jojer (team46)  
42 | 北京化工大学 | 73 | AngryBirds (team123)  
43 | 怀化学院 | 74 | 蓝鸟2 (team105)  
* | 大连理工大学 | 75 | GBM (team126)  
| 北京邮电大学 | 76 | 派 (team71)  
| 东北师范大学 | 77 | 多态 (team19)  
44 | 浙江师范大学 | 78 | 撄宁 (team36)  
| 北京交通大学 | 79 | 永无止境 (team37)  
45 | 哈尔滨工程大学 | 80 | 梦之奇迹 (team144)  
| 西安交通大学 | 81 | Smarabbit (team129)  
46 | 中国地质大学（武汉） | 82 | 南望山 (team146)  
47 | 安徽大学 | 83 | ahu_chorus (team81)  
47 | 北京信息科技大学 | 83 | 卡布奇诺 (team141)  
49 | 西南科技大学 | 85 | 贡嘎雪山 (team137)  
50 | 山东理工大学 | 86 | Loda_影魔 (team127)  
50 | 同济大学 | 86 | Molecule (team128)  
52 | 南开大学 | 88 | THRILLING HOT VI (team96)  
* | 大连理工大学 | 89 | 小Y (team154)  
53 | 重庆大学 | 90 | .铃科丶百合子 (team1)  
| 山东大学 | 91 | SuperBrother (team93)  
* | 哈尔滨工业大学 | 92 | 时间原点 (team148)  
| 杭州电子科技大学 | 93 | 坑爹啊~ (team68)  
54 | 合肥工业大学 | 94 | 工大雷克斯 (team63)  
55 | 浙江中医药大学 | 95 | 杰哥带我们来打酱油 (team67)  
56 | 北京理工大学 | 96 | 愤怒的蚂蚁 (team62)  
尤其是北大的《弱爆了》。。。。。
